config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin, only: [:index]

  namespace :admin do
    resources :reviews, only: [:index, :destroy]
    resources :chats, only: [:index, :destroy]
  end

  root 'games#index'

  resources :credits, only: [:index]

  resources :games, only: [:create, :index, :new, :destroy] do
    collection do
      get 'highscores'
      get 'credits'
      get 'chatroom'
      post 'easy'
      post 'hard'
    end
    resources :paths, :path =>
    '/', :path_names => {
      :red => "",
      :green => "",
      :cyan => "",
      :white => "",
      :purple => "",
      :orange => "",
      :darkred => "",
      :pink => "",
      :yellow => "",
      :blue => "",
      :win => ""}, only: [:create, :new, :destroy] do
      collection do
        get 'red', :path => "/#{SecureRandom.hex(3)}"
        get 'green', :path => "/#{SecureRandom.hex(3)}"
        get 'cyan', :path => "/#{SecureRandom.hex(3)}"
        get 'white', :path => "/#{SecureRandom.hex(3)}"
        get 'purple', :path => "/#{SecureRandom.hex(3)}"
        get 'orange', :path => "/#{SecureRandom.hex(3)}"
        get 'darkred', :path => "/#{SecureRandom.hex(3)}"
        get 'pink', :path => "/#{SecureRandom.hex(3)}"
        get 'yellow', :path => "/#{SecureRandom.hex(3)}"
        get 'blue', :path => "/#{SecureRandom.hex(3)}"
        get 'win', :path => "/#{SecureRandom.hex(3)}"
      end
    end
  end

  resources :highscores, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new]
  resources :chats, only: [:index, :create, :new]

end

app/models/path.rb
class Path < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController

  def red
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.red_boxes.split(', ')
    if @path.current_path == ""
      @path.current_path << "Red, "
    else
      flash.now[:notice]= "HAHA!"
    end
    @path.save!
  end

  def green
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.green_boxes.split(', ')
    @path.current_path << "Green, "
    if @game.hard == true
      flash.now[:notice]= "So it begins..."
    elsif @game.easy == true
      flash.now[:notice]= "Ahh you dipped your feet in"
    else
      flash.now[:notice]= "Once upon a time there was a square"
    end
    @path.save!
  end

  def cyan
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.cyan_boxes.split(', ')
    @path.current_path << "Cyan, "
    @path.save!
    if @game.hard == true
      flash.now[:notice]= "Come at me bro!"
    elsif @game.easy == true
      flash.now[:notice]= "Refreshing isn't it?"
    else
      flash.now[:notice]= "He wished he was a circle"
    end
  end

  def orange
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.orange_boxes.split(', ')
    @path.current_path << "Orange, "
    if @game.hard == true
      flash.now[:notice]= "Now we get serious."
    elsif @game.easy == true
      flash.now[:notice]= "You think you got this?"
    else
      flash.now[:notice]= "Choices... choices"
    end
    @path.save!
  end

  def purple
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.purple_boxes.split(', ')
    @path.current_path << "Purple, "
    if @game.hard == true
      flash.now[:notice]= "A/S/L?"
    else
      flash.now[:notice]= "Just give up."
    end
    @path.save!
  end

  def white
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.white_boxes.split(', ')
    @path.current_path << "White, "
    if @game.hard == true
      flash.now[:notice]= "Halfway There. You Square."
    else
      flash.now[:notice]= "Its not that one."
    end
    @path.save!
  end

  def darkred
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.darkred_boxes.split(', ')
    @path.current_path << "Darkred, "
    if @game.hard == true
      flash.now[:notice]= "Ohoho Someones Smart!"
    else
      flash.now[:notice]= "Winner winner chicken dinner?"
    end
    @path.save!
  end

  def pink
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.pink_boxes.split(', ')
    @path.current_path << "Pink, "
    flash.now[:notice]= "O snap son u think you got this?!"
    @path.save!
  end

  def yellow
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.yellow_boxes.split(', ')
    @path.current_path << "Yellow, "
    flash.now[:notice]= "SO CLOSEEEEE! NOW PRESS THAT ONE!"
    @path.save!
  end

  def blue
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    @path_array = @path.blue_boxes.split(', ')
    @path.current_path << "Blue, "
    flash.now[:notice]= "DONT MESS UP!!"
    @path.save!
  end

  def win
    @game = Game.find_by(id: params[:game_id])
    @path = Path.find_by(game_id: params[:game_id])
    @highscore = Highscore.find_by(game_id: @game.id)
    if current_user
      @highscore.user_id = current_user.id
    end
    @current_path_array = @path.current_path.split(',')
    @winning_path_array = @game.correct_path.split(',')
    @points = @current_path_array.length - @winning_path_array.length
    @highscore.scores = (100000 - (@points * 125))
    @highscore.save
    @game.save
  end

end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/paths/blue.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/blue.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>

<ul id="nav-two">
  <ul class="blue-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/cyan.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/cyan.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>

<ul id="nav-two">
  <ul class="cyan-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/darkred.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/darkred.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>

<ul id="nav-two">
  <ul class="darkred-boxes" id="buttons" style ="position:relative;margin: auto;width: 700px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/green.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/green.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>


<ul id="nav-two">
  <ul class="boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/orange.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/orange.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>


<ul id="nav-two">
  <ul class="orange-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/pink.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/pink.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>


<ul id="nav-two">
  <ul class="pink-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/purple.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/purple.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>


<ul id="nav-two">
  <ul class="purple-boxes" id="buttons" style ="position:relative;margin: auto;width: 700px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/red.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/custom.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>


<ul id="nav-two">
  <ul class="red-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/white.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/white.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1 style="color:black"><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>

<ul id="nav-two">
  <ul class="white-boxes" id="buttons" style ="position:relative;margin: auto;width: 675px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/win.html.erb
<%= content_for :extra_footer do %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href="/assets/zcustom.css" media="screen" rel="stylesheet">
<% end %>

<body bgcolor="#DA4545">

<h1><%=@path.win_boxes%></h1>
  <h2 style="color:white">You Win! Can you do it again though?</h2>
  <h3 style="color:white;text-align:center">Highscore: <%=@highscore.scores%></h3>
    <ul id="nav-two">
      <ul class="peri-boxes" id="buttons" style ="position:relative;margin: auto;width: 450px;">
        <li>
          <a class="green box gas" onmouseover="playclip();" <%= link_to "Play Again", new_game_path%>
          </a>
        </li>
        <li>
          <a class="green box gas" onmouseover="playclip();" <%= link_to "Highscores", highscores_path%>
          </a>
        </li>
        <li>
          <a class="green box gas" onmouseover="playclip();"
           <%= link_to "Rate Us or Hate Us", reviews_path%>
           </a>
        </li>
        <li>
          <a class="green box gas" onmouseover="playclip();"
           <%= link_to "Buy us a beer", "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=AKMDTWRAEEKA4&lc=US&item_name=Red%20Game%20Studios&item_number=Red%20Game%20Studios&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted", :target => "_blank"%>
           </a>
        </li>
      <audio id="beep-two">
      <source src="/assets/hover.mp3" controls></source>
      <source src="/assets/click.ogg" controls></source>
      </audio>
      </ul>
    </ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/paths/yellow.html.erb
<%= content_for :extra_footer do %>
  <link href="/assets/yellow.css" media="screen" rel="stylesheet">
<% end %>

<nav style = "text-align:left">
  <ul>
    <li>
      <%= link_to "Give up?", game_path(@game), :method => :delete %>
    </li>
  </ul>
</nav>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <h1 style="color:black"><%= flash[:notice]%></h1>
    </div>
  </div>
<%end%>

<ul id="nav-two">
  <ul class="yellow-boxes" id="buttons" style ="position:relative;margin: auto;width: 750px;">
    <%@path_array.each do |paths|%>
      <li>
        <a class="green box gas" onmouseover="playclip();" <a style="cursor: pointer" onclick="javascript: window.location = '<%=paths%>'" </a></a>
      </li>
    <%end%>
  <audio id="beep-two">
  <source src="/assets/hover.mp3" controls></source>
  <source src="/assets/click.ogg" controls></source>
  </audio>
  </ul>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>