config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin, only: [:index]

  namespace :admin do
    resources :reviews, only: [:index, :destroy]
    resources :chats, only: [:index, :destroy]
  end

  root 'games#index'

  resources :credits, only: [:index]

  resources :games, only: [:create, :index, :new, :destroy] do
    collection do
      get 'highscores'
      get 'credits'
      get 'chatroom'
      post 'easy'
      post 'hard'
    end
    resources :paths, :path =>
    '/', :path_names => {
      :red => "",
      :green => "",
      :cyan => "",
      :white => "",
      :purple => "",
      :orange => "",
      :darkred => "",
      :pink => "",
      :yellow => "",
      :blue => "",
      :win => ""}, only: [:create, :new, :destroy] do
      collection do
        get 'red', :path => "/#{SecureRandom.hex(3)}"
        get 'green', :path => "/#{SecureRandom.hex(3)}"
        get 'cyan', :path => "/#{SecureRandom.hex(3)}"
        get 'white', :path => "/#{SecureRandom.hex(3)}"
        get 'purple', :path => "/#{SecureRandom.hex(3)}"
        get 'orange', :path => "/#{SecureRandom.hex(3)}"
        get 'darkred', :path => "/#{SecureRandom.hex(3)}"
        get 'pink', :path => "/#{SecureRandom.hex(3)}"
        get 'yellow', :path => "/#{SecureRandom.hex(3)}"
        get 'blue', :path => "/#{SecureRandom.hex(3)}"
        get 'win', :path => "/#{SecureRandom.hex(3)}"
      end
    end
  end

  resources :highscores, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new]
  resources :chats, only: [:index, :create, :new]

end

app/views/admin/index.html.erb
<nav>
  <ul>
    <li>
      <%= link_to "Back", games_path%>
    </li>
  </ul>
</nav>
<%= content_for :extra_footer do %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
<%end%>

<h1>Admin Page</h1>

<div style="text-align:center;font-size:200%"><%= link_to "Reviews", admin_reviews_path %></div>
<div style="text-align:center;font-size:200%"><%= link_to "Chats", admin_chats_path %></div>