config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin, only: [:index]

  namespace :admin do
    resources :reviews, only: [:index, :destroy]
    resources :chats, only: [:index, :destroy]
  end

  root 'games#index'

  resources :credits, only: [:index]

  resources :games, only: [:create, :index, :new, :destroy] do
    collection do
      get 'highscores'
      get 'credits'
      get 'chatroom'
      post 'easy'
      post 'hard'
    end
    resources :paths, :path =>
    '/', :path_names => {
      :red => "",
      :green => "",
      :cyan => "",
      :white => "",
      :purple => "",
      :orange => "",
      :darkred => "",
      :pink => "",
      :yellow => "",
      :blue => "",
      :win => ""}, only: [:create, :new, :destroy] do
      collection do
        get 'red', :path => "/#{SecureRandom.hex(3)}"
        get 'green', :path => "/#{SecureRandom.hex(3)}"
        get 'cyan', :path => "/#{SecureRandom.hex(3)}"
        get 'white', :path => "/#{SecureRandom.hex(3)}"
        get 'purple', :path => "/#{SecureRandom.hex(3)}"
        get 'orange', :path => "/#{SecureRandom.hex(3)}"
        get 'darkred', :path => "/#{SecureRandom.hex(3)}"
        get 'pink', :path => "/#{SecureRandom.hex(3)}"
        get 'yellow', :path => "/#{SecureRandom.hex(3)}"
        get 'blue', :path => "/#{SecureRandom.hex(3)}"
        get 'win', :path => "/#{SecureRandom.hex(3)}"
      end
    end
  end

  resources :highscores, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new]
  resources :chats, only: [:index, :create, :new]

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path, notice: "Review successfully deleted."
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @review = Review.new
    @reviews = Review.all.order('created_at DESC')
  end

  def create
    @review = Review.new(review_params)
    if current_user
      @review.user_id = current_user.id
    else
      @review.user_id = 0
    end
    if @review.save
      respond_to do |format|
        format.html { redirect_to reviews_path, notice: "Game Rated!" }
        format.json { render :show }
      end
    else
      respond_to do |format|
        format.html { render reviews_path }
        format.json
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:message, :rating)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<%= content_for :extra_footer do %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href="/assets/zcustom.css" media="screen" rel="stylesheet">
<% end %>

<nav>
  <ul>
    <li>
      <%= link_to "Back", games_path%>
    </li>
  </ul>
</nav>

<h1>Reviews</h1>

<body bgcolor="#DA4545">
  <%if @reviews%>
    <%@reviews.each do |r|%>
      <div style="text-align:center;font-size:200%">
        <%if r.user%>
          <%=r.user.username + ":"%>
        <%else%>
          <%="Anonymous:"%>
        <%end%>
          <%=r.message%>
          <%=r.rating%>
          <%= link_to 'Delete', admin_review_path(r), method: :delete  %>
      </div>
    <%end%>
  <%end%>

</body>