config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin, only: [:index]

  namespace :admin do
    resources :reviews, only: [:index, :destroy]
    resources :chats, only: [:index, :destroy]
  end

  root 'games#index'

  resources :credits, only: [:index]

  resources :games, only: [:create, :index, :new, :destroy] do
    collection do
      get 'highscores'
      get 'credits'
      get 'chatroom'
      post 'easy'
      post 'hard'
    end
    resources :paths, :path =>
    '/', :path_names => {
      :red => "",
      :green => "",
      :cyan => "",
      :white => "",
      :purple => "",
      :orange => "",
      :darkred => "",
      :pink => "",
      :yellow => "",
      :blue => "",
      :win => ""}, only: [:create, :new, :destroy] do
      collection do
        get 'red', :path => "/#{SecureRandom.hex(3)}"
        get 'green', :path => "/#{SecureRandom.hex(3)}"
        get 'cyan', :path => "/#{SecureRandom.hex(3)}"
        get 'white', :path => "/#{SecureRandom.hex(3)}"
        get 'purple', :path => "/#{SecureRandom.hex(3)}"
        get 'orange', :path => "/#{SecureRandom.hex(3)}"
        get 'darkred', :path => "/#{SecureRandom.hex(3)}"
        get 'pink', :path => "/#{SecureRandom.hex(3)}"
        get 'yellow', :path => "/#{SecureRandom.hex(3)}"
        get 'blue', :path => "/#{SecureRandom.hex(3)}"
        get 'win', :path => "/#{SecureRandom.hex(3)}"
      end
    end
  end

  resources :highscores, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new]
  resources :chats, only: [:index, :create, :new]

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :paths
  has_many :highscores
  has_many :users, through: :highscores
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @user = current_user
  end

  def new
    @user = current_user
  end

  def hard
    @game = Game.create(correct_path: "Red,Green,Cyan,Orange,Purple,White,Darkred,Pink,Yellow,Blue", hard: true)
    @highscore = Highscore.create(scores: 0, user_id: 0, game_id: @game.id)
    @path = Path.new
    @path.current_path = ""
    @path.game_id = @game.id
    if current_user
      @path.user_id = current_user.id
    else
      @path.user_id = 0
    end

    red_boxes = Array.new
    9.times do
      red_boxes << green_game_paths_path(@game.id)
    end

    @path.red_boxes = red_boxes.shuffle.join(', ')

    green_boxes = [
      cyan_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id)
       ]

    @path.green_boxes = green_boxes.shuffle.join(', ')

    cyan_boxes = [
      orange_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      green_game_paths_path(@game.id)
       ]

    @path.cyan_boxes = cyan_boxes.shuffle.join(', ')

    orange_boxes = [
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
       ]

    @path.orange_boxes = orange_boxes.shuffle.join(', ')

    purple_boxes = [
      cyan_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      red_game_paths_path(@game.id)
       ]

    @path.purple_boxes = purple_boxes.shuffle.join(', ')

    white_boxes = [
      green_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id)
       ]

    @path.white_boxes = white_boxes.shuffle.join(', ')

    darkred_boxes = [
      green_game_paths_path(@game.id),
      pink_game_paths_path(@game.id),
      pink_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      red_game_paths_path(@game.id)
       ]

    @path.darkred_boxes = darkred_boxes.shuffle.join(', ')

    pink_boxes = [
      yellow_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      red_game_paths_path(@game.id)
       ]

    @path.pink_boxes = pink_boxes.shuffle.join(', ')

    yellow_boxes = [
      red_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id),
      pink_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      pink_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      blue_game_paths_path(@game.id)
       ]

    @path.yellow_boxes = yellow_boxes.shuffle.join(', ')

    blue_boxes = [
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      red_game_paths_path(@game.id)
       ]

    @path.blue_boxes = blue_boxes.shuffle.join(', ')

    @path.win_boxes = "Good job you have bested me."

    if current_user
      @path.user_id = current_user.id
      @highscore.user_id = current_user.id
    end
    if @path.save
      redirect_to red_game_paths_path(@game.id), notice: "You aint ready. Much frustration. Such wow."
    end
  end

  def create
    @game = Game.create(correct_path: "Red,Green,Cyan,Orange,Purple,White,Darkred")
    @highscore = Highscore.create(scores: 0, user_id: 0, game_id: @game.id)
    @path = Path.new
    @path.current_path = ""
    @path.game_id = @game.id
    if current_user
      @path.user_id = current_user.id
    else
      @path.user_id = 0
    end

    red_boxes = [
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id)
       ]

    @path.red_boxes = red_boxes.shuffle.join(', ')

    green_boxes = [
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id)
       ]

    @path.green_boxes = green_boxes.shuffle.join(', ')

    cyan_boxes = [
      red_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
       ]

    @path.cyan_boxes = cyan_boxes.shuffle.join(', ')

    orange_boxes = [
      red_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
       ]

    @path.orange_boxes = orange_boxes.shuffle.join(', ')

    purple_boxes = [
      orange_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
       ]

    @path.purple_boxes = purple_boxes.shuffle.join(', ')

    white_boxes = [
      cyan_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
      darkred_game_paths_path(@game.id)
       ]

    @path.white_boxes = white_boxes.shuffle.join(', ')

    darkred_boxes = [
      orange_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      white_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id),
      purple_game_paths_path(@game.id),
      red_game_paths_path(@game.id)
       ]

    @path.darkred_boxes = darkred_boxes.shuffle.join(', ')


    @path.pink_boxes = ""
    @path.yellow_boxes = ""
    @path.blue_boxes = ""

    @path.win_boxes = "Try a harder one next time you pansy."

    if current_user
      @path.user_id = current_user.id
      @highscore.user_id = current_user.id
    end
    if @path.save
      redirect_to red_game_paths_path(@game.id), notice: "O you want more huh?"
    end
  end

  def easy
    @game = Game.create(correct_path: "Red,Green,Cyan,Orange", easy: true)
    @highscore = Highscore.create(scores: 0, user_id: 0, game_id: @game.id)
    @path = Path.new
    @path.current_path = ""
    @path.game_id = @game.id
    if current_user
      @path.user_id = current_user.id
    else
      @path.user_id = 0
    end

    red_boxes = [
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
       ]

    @path.red_boxes = red_boxes.shuffle.join(', ')

    green_boxes = [
      red_game_paths_path(@game.id),
      red_game_paths_path(@game.id),
      cyan_game_paths_path(@game.id)
       ]

    @path.green_boxes = green_boxes.shuffle.join(', ')

    cyan_boxes = [
      red_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
      orange_game_paths_path(@game.id),
       ]

    @path.cyan_boxes = cyan_boxes.shuffle.join(', ')

    orange_boxes = [
      red_game_paths_path(@game.id),
      win_game_paths_path(@game.id),
      green_game_paths_path(@game.id),
       ]

    @path.orange_boxes = orange_boxes.shuffle.join(', ')

    @path.purple_boxes = ""
    @path.pink_boxes = ""
    @path.darkred_boxes = ""
    @path.white_boxes = ""
    @path.yellow_boxes = ""
    @path.blue_boxes = ""

    @path.win_boxes = "That was an easy one."

    if current_user
      @path.user_id = current_user.id
      @highscore.user_id = current_user.id
    end
    if @path.save
      redirect_to red_game_paths_path(@game.id), notice: "GAME STARTO"
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path

  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<%= content_for :extra_footer do %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href="/assets/zcustom.css" media="screen" rel="stylesheet">
<% end %>

<%if @user && @user.admin%>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
      </li>
      <li>
        <%= link_to "Rate Us or Hate Us", reviews_path%>
      </li>
      <li>
        <%= link_to "Admin Page", admin_index_path%>
      </li>
    </ul>
  </nav>
<%elsif @user && !@user.admin%>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
      </li>
      <li>
        <%= link_to "Rate Us or Hate Us", reviews_path%>
      </li>
    </ul>
  </nav>
<%else%>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign In", new_user_session_path%>
      </li>
      <li>
        <%= link_to "Rate Us or Hate Us", reviews_path%>
      </li>
    </ul>
  </nav>
<%end%>

<h1>Red Screen</h1>

<br>

<body bgcolor="#DA4545">

<ul id="nav-two">
  <ul class="peri-boxes" id="buttons" style ="position:relative;margin: auto;width: 4px; width: 500px;">
    <li>
      <a class="green box gas" <%= link_to "Play", new_game_path%>
      </a>
    </li>
    <li>
      <a class="green box gas" <%= link_to "Highscores", highscores_path%>
      </a>
    </li>
     <li>
    <a class="green box gas" <%= link_to "Chatroom", chats_path%>
      </a>
    </li>
    <li>
      <a class="green box gas" <%= link_to "Credits", credits_path%>
      </a>
    </li>
  </ul>
  <audio id="beep-two">
  <source src="assets/hover.mp3" controls></source>
  <source src="assets/click.ogg" controls></source>
  </audio>
</ul>

<script>$("#nav-two a")
  .each(function(i) {
    if (i != 0) {
      $("#beep-two")
        .clone()
        .attr("id", "beep-two" + i)
        .appendTo($(this).parent());
    }
    $(this).data("beeper", i);
  })
  .mouseenter(function() {
    $("#beep-two" + $(this).data("beeper"))[0].play();
  });
  $("#beep-two").attr("id", "beep-two0");
</script>

app/views/games/new.html.erb
<%= content_for :extra_footer do %>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href="/assets/zcustom.css" media="screen" rel="stylesheet">
<% end %>

<%if @user%>
  <nav>
    <ul>
      <li>
        <%= link_to "Back", games_path%>
      </li>
    </ul>
  </nav>
<%else%>
  <nav>
    <ul>
      <li>
        <%= link_to "Back", games_path%>
      </li>
    </ul>
  </nav>
<%end%>


<body bgcolor="#DA4545">
  <div class="scroller" style ="position:relative;margin: auto;width: 530px;">
    <div>
      <h1><%= link_to "Easy", easy_games_path, :method => :post, style:'color:#FFFFFF;text-decoration:none;'%><h1>
    </div>
    <div>
      <h1><%= link_to "Medium", games_path, :method => :post, style:'color:#FFFFFF;text-decoration:none;' %><h1>
    </div>
    <div>
    <h1><%= link_to "Hard", hard_games_path, :method => :post, style:'color:#FFFFFF;text-decoration:none;' %><h1>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <p style="color:inherit;font-size:30px;text-align:center;font-family:Verdana"> WARNING: a few people may experience seizures when viewing flashing lights.<p  style="color:white;font-size:30px;text-align:center;font-family:Verdana">
  Directions: Follow the order. <p>
  <%if @user%>
    <h4 style="font-family:Verdana;color:#FFFFFF;text-align:center">You ready <%=@user.username%>?</h4>
  <%else%>
    <h4 style="font-family:Verdana;color:#FFFFFF;text-align:center">You must be signed in if you want a highscore</h4>
  <%end%>
  <br>
  <br>
  <div class="youtube" style ="position:relative;margin: auto;width: 530px;">
    <iframe width="560" height="315" src="//www.youtube.com/embed/Y__Q1VJE5OE" frameborder="0" allowfullscreen></iframe>
  </div>
</body>